// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IUyxQqBUYLnq_JPv7HbafJIWeh7YPZs',
    appId: '1:78546251315:web:23fc3b60ab8e362a94fd46',
    messagingSenderId: '78546251315',
    projectId: 'go-garage-55969',
    authDomain: 'go-garage-55969.firebaseapp.com',
    storageBucket: 'go-garage-55969.firebasestorage.app',
    measurementId: 'G-6S6QKW1DJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l5_ODa0FXlINNfy-oIgFXxriUbElEEk',
    appId: '1:78546251315:android:cb6a1a5a700a107794fd46',
    messagingSenderId: '78546251315',
    projectId: 'go-garage-55969',
    storageBucket: 'go-garage-55969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6d1yoAmhL8ey816JLQW6lArgORA2YQuQ',
    appId: '1:78546251315:ios:ca697624ab2ee10294fd46',
    messagingSenderId: '78546251315',
    projectId: 'go-garage-55969',
    storageBucket: 'go-garage-55969.firebasestorage.app',
    iosBundleId: 'com.example.garagePlantMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6d1yoAmhL8ey816JLQW6lArgORA2YQuQ',
    appId: '1:78546251315:ios:ca697624ab2ee10294fd46',
    messagingSenderId: '78546251315',
    projectId: 'go-garage-55969',
    storageBucket: 'go-garage-55969.firebasestorage.app',
    iosBundleId: 'com.example.garagePlantMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2IUyxQqBUYLnq_JPv7HbafJIWeh7YPZs',
    appId: '1:78546251315:web:d93328667b9b6b7394fd46',
    messagingSenderId: '78546251315',
    projectId: 'go-garage-55969',
    authDomain: 'go-garage-55969.firebaseapp.com',
    storageBucket: 'go-garage-55969.firebasestorage.app',
    measurementId: 'G-LP6DZ18YXY',
  );

}